# Generated by Django 6.0 on 2025-12-23 21:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('rango_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rango_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_referencia', models.CharField(help_text='Código médico o término de búsqueda', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Médico'), ('ADMIN', 'Administrador')], default='PACIENTE', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_examen', models.DateField()),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('NORMAL', 'Normal'), ('ALTO', 'Alto')], editable=False, max_length=10)),
                ('observaciones_medline', models.TextField(blank=True, null=True)),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='examenes_adjuntos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('examen_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.catalogoexamen')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_examenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_examen'],
            },
        ),
    ]
