# Generated by Django 6.0 on 2025-12-31 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=50)),
                ('rango_bajo', models.FloatField()),
                ('rango_normal', models.FloatField()),
                ('rango_alto', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='resultadoexamen',
            name='examen_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.catalogoexamen'),
        ),
        migrations.AlterField(
            model_name='resultadoexamen',
            name='nivel_riesgo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resultadoexamen',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resultadoexamen',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
